<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos [
    <!ELEMENT alumnos (alumno+)>
      <!ELEMENT alumno (nombre+,edad+,fecha_nacimiento?,hijo?)>
      <!ATTLIST alumno lugar ID #REQUIRED >
      
            <!ELEMENT nombre (#PCDATA)>
            <!ATTLIST nombre dni CDATA #IMPLIED >

            <!ELEMENT edad (#PCDATA)>
            <!ELEMENT fecha_nacimiento (#PCDATA)>
            <!ELEMENT hijo (#PCDATA)>
]>

<alumnos>
  <alumno lugar="Afuera">
    <nombre dni="44566820R">tablero</nombre>
    <edad>14</edad>
    <fecha_nacimiento>1990-10-10</fecha_nacimiento>
    <hijo>Raul</hijo>
  </alumno>
</alumnos>